version: '4.0'
services:
  irc:
    build: ./irc
    image: hullseals/unrealircd
    ports:
      - "6667:6667" # for IRC
      - "6697:6697" # for IRC

  services:
    build: ./irc_services
    image: hullseals/anope_services

    links:
      - irc
